export const APP_COPYRIGHT = '© D-diviser App 2022.'
export const MADE_WITH = ' Made with '
export const HEART = '♥'
export const BY = ' by '
export const AUTHOR_NAME = '@sphingu'
export const AUTHOR_LINK = 'https://github.com/sphingu'
